POST http://localhost:3001/api/campgrounds/63a3575b483adecb596347ff/comments


Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MDM5NjkyNThkMjhhNTNmMDYyMGMxMCIsImlhdCI6MTY3Nzk1Njc1NCwiZXhwIjoxNjgwNTQ4NzU0fQ.aRaqj9VPIMXyZQNCH4XSagB7ygdWiQ6AR4vhSCRBHAA


{
  "comment": "Brown County State Park",
  
}